name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "."
          target: "/var/www/swm"
          script: |
                sudo tar -czf /var/www/swm/app.tar.gz .
                sudo tar -xzf /var/www/swm/app.tar.gz -C /var/www/swm
                cd /var/www/swm
                ng build
                cp -a /var/www/swm/docs/. /var/www/html/
